{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6aa44cc4-64b8-4a1c-a00f-fda4be5ccba1",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "k = 10\n",
    "\n",
    "F0 = 12       \n",
    "k = 10.0      \n",
    "# D = 0.05      \n",
    "# beta = 1.6e-4 \n",
    "# b = beta * D \n",
    "b=.1\n",
    "F0 = 5.0      \n",
    "omega_d = 6.0  \n",
    "m = 0.1  \n",
    "\n",
    "1/4*(b/m)**2 == k/m\n",
    "b**2 == m*k*4\n",
    " \n",
    "def force(t, x, v, omega_d):\n",
    "    return -k * x - b * v + F0 * np.cos(omega_d * t)\n",
    "\n",
    "\n",
    "\n",
    "nsteps = 1000\n",
    "t_max = 20\n",
    "\n",
    "\n",
    "x0 = 1   \n",
    "v0 = 0 \n",
    "w0 = np.sqrt(k/m)\n",
    "F0 = 2.5\n",
    "\n",
    "nsteps = 1000  # Number of steps\n",
    "\n",
    "\n",
    "t, dt = np.linspace(0, 20, nsteps, retstep=True)\n",
    "\n",
    "\n",
    "data = np.zeros((nsteps, 2))\n",
    "\n",
    "pos = x0\n",
    "vel = v0\n",
    "for i, ti in enumerate(t):\n",
    "    acc = force(ti, pos, vel, omega_d)/m\n",
    "    vel = vel + acc * dt\n",
    "    pos = pos + vel * dt\n",
    "    data[i] = t[i], pos\n",
    "\n",
    "        \n",
    "       \n",
    "analytical = x0 * np.cos( w0 * t)\n",
    "print(b**2)\n",
    "print(4*m*k)\n",
    "\n",
    "plt.plot(data[:,0],data[:,1]) \n",
    "plt.legend()\n",
    "\n",
    "plt.savefig()\n",
    "plt.savefig(\"Phingegee.png\")\n",
    "plt. close()\n",
    "\n",
    "\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
